name: My build and deploy action

env:
  AZURE_WEBAPP_NAME: myTestappWebNico8034

on:
  push:
    branches:
      - main
        
permissions:
  contents: 'read'
  packages: 'write'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to container registry
        run: |
          docker login https://ghcr.io -u ${{ secrets.DOCKER_USERNAME}} -p ${{ secrets.DOCKER_KEY}}
      
      - name: Build and push image to registry
        run: |
          docker buildx build --push -t ${{ secrets.DOCKER_TAG }} .
          
  deploy:
    runs-on: ubuntu-latest

    needs: build
   
    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@0b651ed7546ecfc75024011f76944cb9b381ef1e
          with:
            app-name: ${{ env.AZURE_WEBAPP_NAME }}
            publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
            images: 'ghcr.io/nico8034/testapp/backend'
      
    